### PR TITLE
fix east asian ambiguous runes

### PR DESCRIPTION
**Pull request by hamano**
BOX DRAWINGS(─) and ARROW(↑￼→￼↓￼←) are East Asian Ambiguous charactors.
http://unicode.org/reports/tr11/
So they break ascii art depends on terminal or locale.
We need to option that allow to switch half width and full width for EAW charactors.
This is my first aid patch:
Thank you.

Original:
orig

Fixed:
fix

### CODE REVIEW

**Comment by schachmat** [comment]
Heyho @hamano 

thanks for reporting this. You PR just is a workaround, so I want to fix it in a proper way. Unfortunately I can not reproduce this issue just by setting the LANG or LC_CTYPE environment variables to "ja_JP.UTF-8" (after generating this locale of course). Can you help me reproduce it?

**Comment by hamano** [comment]
In xterm:
xterm -cjk_width will display ─ as full width.
xterm +cjk_width will display ─ as half width.
please note that runewidth.StringWidth("─") return width depends on glibc locale.
This is pretty complication issue, so I propose just add flag that switch "─" and "-".
Thank you.

**Comment by schachmat** [comment]
Thanks for the hint @hamano, I managed to reproduce your problem when I run `LC_CTYPE="ja_JP.UTF-8" wego` in this `xterm -cjk_width` terminal.

I already pushed a fix for the arrows, degree sign and dashes between numbers last night, so it looks less obstructed already. There are two points left:

- [ ] In the Icons for some raindrops I use the `LEFT SINGLE QUOTATION MARK` (U+2018) and `RIGHT SINGLE QUOTATION MARK` (U+2019) unicode characters, which have east asian ambiguous width. I did not find a good looking replacement for them yet, The `SINGLE HIGH-REVERSED-9 QUOTATION MARK` (U+201B) has the wrong orientation and the `ACUTE ACCENT` (U+00B4) is too thin and too angled. If anyone has a good suggestion, let me know.
- [ ] The box drawing characters of course.

For the box drawing characters I plan to extract the table-building process into a separate library which is able to handle all unicode codepoints and even ANSI escape codes and still paint pretty tables with the boxdrawing characters instead of just normal dashes, pipes and plus signs.

A little note: using `runewidth.EastAsianWidth` is easier than `runewidth.StringWidth("─") == 2`.

**Comment by hamano** [comment]
> In the Icons for some raindrops I use the LEFT SINGLE QUOTATION MARK (U+2018) and RIGHT SINGLE QUOTATION MARK (U+2019) unicode characters, which have east asian ambiguous width. I did not find a good looking replacement for them yet, The SINGLE HIGH-REVERSED-9 QUOTATION MARK (U+201B) has the wrong orientation and the ACUTE ACCENT (U+00B4) is too thin and too angled. If anyone has a good suggestion, let me know.

Originally, you expected half width for raindrop.
Why don't you use '(U+0027 APOSTROPHE) and `(U+0060 GRAVE ACCENT)?

> For the box drawing characters I plan to extract the table-building process into a separate library which is able to handle all unicode codepoints and even ANSI escape codes and still paint pretty tables with the boxdrawing characters instead of just normal dashes, pipes and plus signs.

I am looking forward your fix.
Thank you.

**Comment by schachmat** [comment]
Wow, that's a great list. How did you come up with it? Is there some lookalike-codepoint-website?

I decided to use the MODIFIER LETTER TURNED COMMA and the GREEK PSILI. All the icons should now work properly, if you find one, that is still misaligned, let me know.

[gobular](https://github.com/schachmat/gobular) will replace the table rendering, when it's done.

**Comment by hamano** [comment]
I foud these charactors from here:
http://shapecatcher.com/
It's usefull when drawing AA.

BTW, now I can't build wego. some thing wrong?
~~~
% go version
go version go1.3.3 linux/amd64
% go get -v -u github.com/schachmat/wego
github.com/schachmat/wego (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-runewidth (download)
github.com/schachmat/ingo (download)
github.com/schachmat/ingo
# github.com/schachmat/ingo
lib/go/src/github.com/schachmat/ingo/in.go:92: undefined: flag.UnquoteUsage
~~~

**Comment by schachmat** [comment]
That's a nice ressource, thanks!

Since adding ingo as dependency wego needs go >=1.5. If your package management system does not have 1.5 yet, you can either install go manually or use goenv as linked in the README.

**Comment by hamano** [comment]
Ok, Thanks.
worked with golang 1.6
